;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                General.inc                                 ;
;                                 Homework3                                  ;
;                                Sunghoon Choi                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Description:      
;     This file contains definitions for general constants.             
;                   
; Revision History:    
;          10/21/2016    Sunghoon Choi    Initial Revision
;          10/22/2016    Sunghoon Choi    Added Comments
;          11/26/2016    Sunghoon Choi    Added DECIMAL_BASE

TRUE            EQU     1        ;LOGIC TRUE
FALSE           EQU     0        ;LOGIC FALSE
ZERO            EQU     0        ;INTEGER 0
MULT_BY_2       EQU     1        ;The constant used in SHL operation to multiply by 2
DECIMAL_BASE    EQU     10       ;Base of decimal numbers.

ASCII_NULL      EQU     0        ;ASCII Null
CARRIAGE_RETURN EQU     13       ;ASCII Carriage Return
STARTING_INDEX  EQU     0        ;Starting index for arrays