;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 Remote.inc                                 ;
;                                 Homework 9       	    					 ;
;							     Sunghoon Choi                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Description: 
;  This file contains the definitions for the constants of Remote.asm
;
; Revision History:
;     12/01/2016    Sunghoon Choi      Created
;	  12/02/2016	Sunghoon Choi	   Initial Compilation
;	  12/02/2016    Sunghoon Choi      Updated documentation   

COMMAND_LENGTH    	EQU		 8	;Length of each RoboTrike motor commands
REMOTE_BUFFER_LEN 	EQU 	 9  ;The length of RemoteDisplayBuffer
